export const EmailEvent = {
    USER_REGISTERED: 'USER_REGISTERED',
    USER_VERIFIED: 'USER_VERIFIED',
    PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    
    EVENT_CREATED: 'EVENT_CREATED',
    EVENT_UPDATED: 'EVENT_UPDATED',
    EVENT_REMINDER: 'EVENT_REMINDER',
    EVENT_CANCELLED: 'EVENT_CANCELLED',
    EVENT_COMPLETED: 'EVENT_COMPLETED',
    REGISTRATION_CONFIRMED: 'REGISTRATION_CONFIRMED',
    EVENT_APPROVED: 'EVENT_APPROVED',
    EVENT_REJECTED: 'EVENT_REJECTED',
    ATTENDANCE_CONFIRMED: 'ATTENDANCE_CONFIRMED',
    REWARD_EARNED: 'REWARD_EARNED',
    
    BADGE_EARNED: 'BADGE_EARNED',
    POINTS_AWARDED: 'POINTS_AWARDED',
    LEADERBOARD_RANK_IMPROVED: 'LEADERBOARD_RANK_IMPROVED',
    WEEKLY_LEADERBOARD_SUMMARY: 'WEEKLY_LEADERBOARD_SUMMARY',
    MILESTONE_REACHED: 'MILESTONE_REACHED',
    STREAK_WARNING: 'STREAK_WARNING',
    
    WEEKLY_ANALYTICS_REPORT: 'WEEKLY_ANALYTICS_REPORT',
    MONTHLY_ENGAGEMENT_REPORT: 'MONTHLY_ENGAGEMENT_REPORT',
    REPORT_EXPORT_READY: 'REPORT_EXPORT_READY',
    SCHEDULED_REPORT_DELIVERY: 'SCHEDULED_REPORT_DELIVERY',
    REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',
    
    APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
    APPROVAL_DECISION: 'APPROVAL_DECISION',
    RULE_CONFIG_CHANGED: 'RULE_CONFIG_CHANGED',
    LARGE_POINT_ADJUSTMENT: 'LARGE_POINT_ADJUSTMENT',
    SYSTEM_FAILURE: 'SYSTEM_FAILURE',
    AUDIT_NOTIFICATION: 'AUDIT_NOTIFICATION',
} as const;

export type EmailEventType = typeof EmailEvent[keyof typeof EmailEvent];

export const TemplateName = {
    WELCOME: 'welcome',
    VERIFICATION: 'verification',
    PASSWORD_RESET: 'passwordReset',
    PASSWORD_CHANGED: 'passwordChanged',
    SUSPICIOUS_LOGIN: 'suspiciousLogin',
    ACCOUNT_DELETED: 'accountDeleted',
    
    EVENT_CREATED: 'eventCreated',
    EVENT_UPDATED: 'eventUpdated',
    EVENT_REMINDER: 'eventReminder',
    EVENT_CANCELLED: 'eventCancelled',
    EVENT_COMPLETED: 'eventCompleted',
    REGISTRATION_CONFIRMED: 'registrationConfirmed',
    EVENT_APPROVED: 'eventApproved',
    EVENT_REJECTED: 'eventRejected',
    ATTENDANCE_CONFIRMED: 'attendanceConfirmed',
    REWARD_EARNED: 'rewardEarned',
    
    BADGE_EARNED: 'badgeEarned',
    POINTS_AWARDED: 'pointsAwarded',
    LEADERBOARD_RANK_IMPROVED: 'leaderboardRankImproved',
    WEEKLY_LEADERBOARD_SUMMARY: 'weeklyLeaderboardSummary',
    MILESTONE_REACHED: 'milestoneReached',
    STREAK_WARNING: 'streakWarning',
    
    WEEKLY_ANALYTICS_REPORT: 'weeklyAnalyticsReport',
    MONTHLY_ENGAGEMENT_REPORT: 'monthlyEngagementReport',
    REPORT_EXPORT_READY: 'reportExportReady',
    SCHEDULED_REPORT_DELIVERY: 'scheduledReportDelivery',
    REPORT_GENERATION_FAILED: 'reportGenerationFailed',
    
    APPROVAL_REQUIRED: 'approvalRequired',
    APPROVAL_DECISION: 'approvalDecision',
    RULE_CONFIG_CHANGED: 'ruleConfigChanged',
    LARGE_POINT_ADJUSTMENT: 'largePointAdjustment',
    SYSTEM_FAILURE: 'systemAutomationFailure',
    AUDIT_NOTIFICATION: 'auditNotification',
} as const;

export type TemplateNameType = typeof TemplateName[keyof typeof TemplateName];
